# name: Deploy to EC2

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: "20" # Specify your Node.js version

#       - name: Install server dependencies
#         run: |
#           cd server
#           npm install

#       - name: Install client dependencies and build
#         run: |
#           cd client
#           yarn install
#           yarn build

#       - name: Move build files to server public directory
#         run: |
#           rsync -av --delete client/build/ server/public/

#       - name: Archive production artifacts
#         run: zip -r production.zip server

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1 # Replace with your AWS region

#       - name: Upload artifact to S3
#         run: aws s3 cp production.zip s3://robosealersbucket/production.zip # Replace with your S3 bucket name

#       - name: Deploy to EC2 via CodeDeploy
#         run: |
#           aws deploy create-deployment \
#             --application-name RobosealersApp \
#             --deployment-group-name RobosealersAppDeploymentGroup \
#             --s3-location bucket=robosealersbucket,key=production.zip,bundleType=zip

name: Deploy

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{secrets.SSH_HOST}}
          USER_NAME: ${{secrets.USER_NAME}}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              # Now we have got the access of EC2 and we will start the deploy .
              rm -rf moh
              
              cd apps/robosealers-demo-v2
              echo "entered project directory"
            
              git pull
              echo "project updated successfully"

            #   cd client
            #   yarn install
            #   echo "client package installed successfully"
              
            #   rm -rf build
            #   echo "old build deleted successfully"

            #   yarn build
            #   echo "react app build successfully"

            #   rm -rf ../server/public/*
            #   echo "remove public content directory in server"

            #   mv build/* ../server/public/
            #   echo "move build files to server public directory"

              # Stop PM2 applications
              pm2 stop all || true
              echo "stop  all PM2 applications"

              # Start the server
              cd ../server
              npm install
              pm2 start configs/server.js --name robosealers
              echo "start server successfully"

              # Restart Nginx
              sudo systemctl restart nginx
              echo "restart nginx server successfully"
              '
